<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>WinNUT_Client.My.MyApplication</StartupObject>
    <RootNamespace>WinNUT_Client</RootNamespace>
    <MyType>WindowsForms</MyType>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Background</UpdateMode>
    <UpdateInterval>1</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>true</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <InstallUrl>https://nutdotnet.github.io/WinNUT-Client/</InstallUrl>
    <SupportUrl>https://github.com/nutdotnet/WinNUT-Client/issues</SupportUrl>
    <ProductName>WinNUT</ProductName>
    <PublisherName>NUTDotNet</PublisherName>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>0.0.0.0</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>false</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;PreRelease;Release</Configurations>
    <MultilingualAppToolkitVersion>4.0</MultilingualAppToolkitVersion>
    <MultilingualFallbackLanguage>en</MultilingualFallbackLanguage>
    <TranslationReport>true</TranslationReport>
    <SuppressPseudoWarning>true</SuppressPseudoWarning>
    <ApplicationIcon>Resources\WinNut.ico</ApplicationIcon>
    <ManifestCertificateThumbprint>C19146538F0D20A60911FD278DFBE5B16AC3C499</ManifestCertificateThumbprint>
    <ManifestKeyFile>WinNUT-client_TemporaryKey.pfx</ManifestKeyFile>
    <GenerateManifests>false</GenerateManifests>
    <SignManifests>false</SignManifests>
    <TargetZone>LocalIntranet</TargetZone>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>
    </DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>false</DefineTrace>
    <DocumentationFile>
    </DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'PreRelease|AnyCPU'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\PreRelease\</OutputPath>
    <DocumentationFile>
    </DocumentationFile>
    <Optimize>true</Optimize>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>false</DefineDebug>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic.Logging" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharedAssemblyInfo.vb">
      <Link>My Project\SharedAssemblyInfo.vb</Link>
    </Compile>
    <Compile Update="About_Gui.Designer.vb">
      <DependentUpon>About_Gui.vb</DependentUpon>
    </Compile>
    <Compile Update="Controls\CProgressBar.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\UPSVarGauge.Designer.vb">
      <DependentUpon>UPSVarGauge.vb</DependentUpon>
    </Compile>
    <Compile Update="Controls\UPSVarGauge.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Forms\UpdateAvailableForm.Designer.vb">
      <DependentUpon>UpdateAvailableForm.vb</DependentUpon>
    </Compile>
    <Compile Update="Shutdown_Gui.Designer.vb">
      <DependentUpon>Shutdown_Gui.vb</DependentUpon>
    </Compile>
    <Compile Update="List_Var_Gui.Designer.vb">
      <DependentUpon>List_Var_Gui.vb</DependentUpon>
    </Compile>
    <Compile Update="Pref_Gui.Designer.vb">
      <DependentUpon>Pref_Gui.vb</DependentUpon>
    </Compile>
    <Compile Update="UpgradePrefsDialog.designer.vb">
      <DependentUpon>UpgradePrefsDialog.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.8">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.8 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <XliffResource Include="MultilingualResources\WinNUT-client.de-DE.xlf" />
    <XliffResource Include="MultilingualResources\WinNUT-client.fr-FR.xlf" />
    <XliffResource Include="MultilingualResources\WinNUT-client.ru-RU.xlf" />
    <XliffResource Include="MultilingualResources\WinNUT-client.uk-UA.xlf" />
    <XliffResource Include="MultilingualResources\WinNUT-client.zh-CN.xlf" />
    <XliffResource Include="MultilingualResources\WinNUT-Client.zh-TW.xlf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinNUT-Client_Common\WinNUT-Client_Common.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\saveHS.png" />
  </ItemGroup>
  <Target Name="MATPrerequisite" BeforeTargets="PrepareForBuild" Condition="!Exists('$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.ResxResources.targets')" Label="MultilingualAppToolkit">
    <Warning Text="$(MSBuildProjectFile) is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed." />
  </Target>
  <Target Name="BeforeBuild">
    <ItemGroup>
      <AssemblyAttributes Include="AssemblyVersion">
        <_Parameter1>$(Version)</_Parameter1>
      </AssemblyAttributes>
    </ItemGroup>
    <MakeDir Directories="$(IntermediateOutputPath)" />
    <WriteCodeFragment Language="VB" OutputFile="$(IntermediateOutputPath)Version.cs" AssemblyAttributes="@(AssemblyAttributes)" />
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)Version.cs" />
    </ItemGroup>
  </Target>
</Project>